#!/bin/bash

# this is a simple config for herbstluftwm

# _   _ _____ ____  ____ ____ _____ _    _   _ _____ _______        ____  __
#| | | | ____|  _ \| __ ) ___|_   _| |  | | | |  ___|_   _\ \      / /  \/  |
#| |_| |  _| | |_) |  _ \___ \ | | | |  | | | | |_    | |  \ \ /\ / /| |\/| |
#|  _  | |___|  _ <| |_) |__) || | | |__| |_| |  _|   | |   \ V  V / | |  | |
#|_| |_|_____|_| \_\____/____/ |_| |_____\___/|_|     |_|    \_/\_/  |_|  |_|
#


hc() {
    herbstclient "$@"
}
# Permet de ne pas avoir de problème avec les tags caractères spéciaux 
setxkbmap fr

hc emit_hook reload


# Background Images
backgroundImages=$HOME/.config/background/background.jpg 
backgroundLock=$HOME/.config/i3lock/background.png

xsetroot -solid '#000000'
compton --config ~/.config/compton/compton.conf &
feh --bg-scale $backgroundImages &
nm-applet &
# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier
ModA=Alt
ModC=Ctrl
TERM="gnome-terminal"
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-z remove
hc keybind $Mod-q chain . close . remove
hc keybind $Mod-c close
hc keybind $Mod-Return spawn $TERM # use your $TERMINAL with xterm as fallback
hc keybind $ModA-f chain . spawn firefox . use_index 2
hc keybind $ModA-g chain . spawn chromium-browser . use_index 2
#hc keybind $ModA-h chain . spawn qutebrowser . use_index 2
hc keybind $ModA-s chain . spawn spotify . use_index 3
hc keybind $ModA-m chain , spawn $TERM -e $HOME/.config/vifm/scripts/vifmrun ~/ , move_index 4 , use_index 4
hc keybind $ModA-d spawn dmenu_run -i -p ">" # use dmenu
#hc keybind $ModA-F1  spawn $HOME/script/sound/sound.sh # Gestion entée sound
#hc keybind $ModA-F2  spawn $TERM -e ncpamixer # Gestion entée sound
hc keybind $ModA-F3 spawn passmenu # Show passmenu
hc keybind Shift-Up spawn amixer -D pulse sset Master 10%+ #increase volume
hc keybind Shift-Down spawn amixer -D pulse sset Master 10%- #down volume
#hc keybind $ModC-Shift-Up spawn pactl set-sink-volume 1 +10% # Volume Casque wifi
#hc keybind $ModC-Shift-Down spawn pactl set-sink-volume 1 -10% # Volumee Casque wifi
#hc keybind Shift-Up spawn pactl set-sink-volume 0 +10% #Volume screen
#hc keybind Shift-Down spawn pactl set-sink-volume 0 -10% # Volume screen
hc keybind $ModA-s spawn rofi -show drun # rofi
hc keybind $ModA-Print spawn scrot '%Y-%m-%d_%H-%M-%S.png' -e 'mv $f ~/Images/Captures/' # screenshoot

# https://github.com/cac03/i3lock
hc keybind $ModC-$Mod-Return spawn i3lock -i $backgroundLock 


# basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u      chain ,  split   bottom  0.5 , focus down
hc keybind $Mod-o      chain ,  split   right   0.5 , focus right
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags

tag_names=( "  " "  " "  " "  " "  " "  ")
#tag_names=( {1..9} )
tag_keys=( {1..6} 0 )
#tab_keys=( ampersand eacute quotedbl apostrophe parenleft minus egrave underscore ccedilla agrave )
tab_keys=('ampersand' 'eacute' 'quotedbl' 'apostrophe' 'parenleft' 'minus')
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    echo "$i\n" >> tmp/text.txt
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind $ModA-"${tab_keys[$i]}" use_index "$i"
        hc keybind Ctrl-$ModA-"${tab_keys[$i]}" move_index "$i"
    fi
done
# cycle through tags
hc keybind $Mod-comma use_index +1 --skip-visible
hc keybind $Mod-n  use_index -1 --skip-visible

# layouting
#hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-Shift-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#cc241d'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#fe8019'
hc set frame_border_width 0
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#fb4934'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color '#cc241d'
hc attr theme.inner_width 0
hc attr theme.inner_color '#101010'
hc attr theme.border_width 1  
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color '#101010'
hc attr theme.active.inner_color '#454545'
hc attr theme.active.outer_color '#454545'
hc attr theme.background_color '#454545'

hc set window_gap 15
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0


# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' manage=off focus=on 
#hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off focus=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# load layout Tag 1

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done


#hc rule class=Gnome-terminal tag="  "
hc rule class=Firefox tag="  "
hc rule class=Qutebrowser tag="  "
hc rule class=Chromium-browser tag="  "
hc rule class=Spotify tag="  "
hc rule class=Nautilus tag="  " 
hc rule class=Typora tag="  "
hc rule class~'libre.*' tag="  "

